### ISSUE TITLE
Сomplementary

### ISSUE THREAD

**Issue by Dmytro-bit** [andrew4ever/brobots-food-bot#23]
The problem is that after 9:00 you can’t order, for the correction you can add one more variable 
"not marked" and give them some time to make a choice.

**Comment by andrewyazura** [comment]
Even if I add the third option of order, "not marked" is still the same as "false". So "not marked" makes no sense in this case. I close the issue now

**Comment by andrewyazura** [comment]
Opened it by accident, sorry)
